export { default as IconBrush } from './IconBrush.vue';
export { default as IconCircle } from './IconCircle.vue';
export { default as IconDownload } from './IconDownload.vue';
export { default as IconEraser } from './IconEraser.vue';
export { default as IconLine } from './IconLine.vue';
export { default as IconRectangle } from './IconRectangle.vue';
export { default as IconUndo } from './IconUndo.vue';
export { default as IconRedo } from './IconRedo.vue';
export { default as IconTrash } from './IconTrash.vue';